spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: wallet
    password: wallet
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    br.com.recargapay: DEBUG
    org.springframework.web: DEBUG